version: "3"
services:
  platform-api:
    container_name: platform-api
    build: .
    volumes:
      - "./src/:/usr/src/app"
    # command:
    #  - "test"
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
